# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='lecture',
        ),
    ]
