# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0002_auto_20170607_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lecture',
            name='student',
            field=models.ManyToManyField(to='manytomany.Student'),
        ),
    ]
