# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_num', models.CharField(max_length=11)),
                ('from_num', models.CharField(max_length=11)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
