# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0002_auto_20170605_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='persontype',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '선생')], default='student', max_length=10, verbose_name='유형'),
        ),
        migrations.AddField(
            model_name='person',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='introduction_to_models.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], help_text='약간 작게 나왔으니 참고해주세요.', max_length=1, verbose_name='셔츠사이즈'),
        ),
    ]
