# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduction_to_models', '0007_auto_20170608_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(related_name='posts_by_like_user', through='introduction_to_models.PostLike', to='introduction_to_models.User'),
        ),
        migrations.AlterModelTable(
            name='postlike',
            table='introduction_to_models_post_like_users',
        ),
    ]
